### PR TITLE
Fixing Unknown title for PDFs

### LINKED ISSUE #1336: PDFs pages Unknown titles.
screen shot 2018-12-05 at 23 18 51
On some PDF pages for example, Popups > Chart Label, Popups > Barcode Label and Popups > Address Label, the title is unknown

### PR DESCRIPTION
**Pull request by punwai**
PDFs do not display titles as the pages are not stored with titles in. To add labels to PDF files, a structure similar to the committed changes must be employed. I was tempted to change this for ALL PDF files but was not sure how necessary this would be as they may not all be iframes. I am awaiting for @Trodrige 's view on this. 

Fixes #1336

### CODE REVIEW

File: interface/patient_file/label.php [hunk 1]
```diff
@@ -75,5 +75,11 @@
 	$pdf->Add_Label($text);
 }
 
-$pdf->Output();
+$output = $pdf->Output('','S');
+$output = base64_encode($output);
 ?>
+
+<title>Chart Label</title>
```
Comment (muarachmann) [inline interface/patient_file/label.php]: nice catch this does the trick

**Comment by Trodrige** [comment]
@punwai is this supposed to solve the Admind-> Rules problem too? Or should we expect another PR. I still see this
screen shot 2018-12-11 at 8 54 43 am

**Comment by Trodrige** [comment]
This doesn't solve #1321

**Comment by punwai** [comment]
@Trodrige My bad, I was referring to the issue you mentioned in #1321 rather than the main problem. #1325 fixes #1321 :)

File: interface/patient_file/label.php (hunk 1 above)
Comment (aethelwulffe) [reply interface/patient_file/label.php]: Need to check for issues with base64_encode php dependency.
